"""Render Code Brain's cross-session memory into a managed ``AGENTS.md`` section.

Why this exists
---------------
Claude Code and Codex CLI receive Code Brain's memory via the ``SessionStart``
hook (``additionalContext``). Google Antigravity (``agy``) cannot use that path:

  * Antigravity has **no** ``SessionStart`` / ``UserPromptSubmit`` hook event — its
    only lifecycle events are ``PreToolUse``/``PostToolUse``/``PreInvocation``/
    ``PostInvocation``/``Stop``.
  * Antigravity **command** (shell) hooks run but cannot inject model context via
    stdout — context injection (``HookInjectedStep``) is wired only for its SDK /
    declarative hook callers, not ``jsonhook`` command hooks (verified empirically:
    the hook executes but injected steps never reach the model).

Antigravity *does* auto-load ``AGENTS.md`` at session start (verified: agy quoted
this block, including the latest decision, when asked "진행상황?"). So we give agy
the same memory by maintaining a managed block in ``AGENTS.md``, refreshed on
``Stop``/``SessionEnd`` for every agent. The content is produced by the same
``build_context("SessionStart", ...)`` used for Claude/Codex, so all three agents
start from the same snapshot.

Safety: never raise into the hook hot path (callers wrap in try/except), write
only when the rendered block actually changed, and stay opt-out via
``AI_AGENTS_MD_MEMORY=0``.
"""
from __future__ import annotations

import os
from pathlib import Path

START = "<!-- CODE-BRAIN:MEMORY:START (auto-generated by Code Brain; do not edit by hand) -->"
END = "<!-- CODE-BRAIN:MEMORY:END -->"
_HEADING = "## Code Brain — cross-agent 메모리 스냅샷 (세션 시작 시 자동 로드)"
_SUPPRESS_ENV = (
    "AI_SKILL_RECOMMENDATIONS",
    "AI_AGENT_RECOMMENDATIONS",
    "AI_PRECALL_RECOMMENDATIONS",
)


def enabled() -> bool:
    return os.environ.get("AI_AGENTS_MD_MEMORY", "1").lower() not in {"0", "false", "no", "off"}


def render_block(root: Path) -> str:
    """Build the memory body — same content Claude/Codex get at SessionStart.

    Recommendation sections are suppressed (as they are for Claude/Codex's
    SessionStart command) so the rules file stays focused on durable memory.
    The transient ``Code Brain fast_path: ...`` header line is dropped.
    """
    saved = {k: os.environ.get(k) for k in _SUPPRESS_ENV}
    for k in _SUPPRESS_ENV:
        os.environ[k] = "0"
    try:
        from .hooks import build_context

        body = build_context("SessionStart", {"agent": "antigravity", "dry": True}, root=root)
    finally:
        for k, v in saved.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v
    if not body:
        return ""
    lines = body.split("\n")
    if lines and lines[0].startswith("Code Brain fast_path:"):
        lines = lines[1:]
        while lines and not lines[0].strip():
            lines = lines[1:]
    return "\n".join(lines).strip()


def compose(existing: str, block: str) -> str:
    """Return ``existing`` with the managed section set to ``block`` (idempotent)."""
    section = f"{START}\n{_HEADING}\n\n{block}\n{END}"
    if START in existing and END in existing:
        pre = existing.split(START, 1)[0]
        post = existing.split(END, 1)[1]
        return f"{pre.rstrip()}\n\n{section}\n{post.lstrip()}".rstrip() + "\n"
    return f"{existing.rstrip()}\n\n{section}\n"


def refresh(root: Path, *, path: str = "AGENTS.md") -> bool:
    """Refresh the managed block in ``<root>/AGENTS.md``. Returns True if written.

    No-op (returns False) when disabled, when there is no memory to render, or
    when the file already matches — so it does not churn AGENTS.md every turn.
    """
    if not enabled():
        return False
    block = render_block(root)
    if not block:
        return False
    target = root / path
    existing = target.read_text(encoding="utf-8") if target.exists() else "# AGENTS.md\n"
    new_text = compose(existing, block)
    if target.exists() and existing == new_text:
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(new_text, encoding="utf-8")
    return True
