"""Render Code Brain's cross-session memory into a managed block in ``AGENTS.md``.

Why this exists
---------------
Claude Code and Codex CLI receive Code Brain's memory via the ``SessionStart`` hook
(``additionalContext``). Google Antigravity (``agy``) cannot use that path:

  * Antigravity has **no** ``SessionStart`` / ``UserPromptSubmit`` hook event — its only
    lifecycle events are ``PreToolUse``/``PostToolUse``/``PreInvocation``/``PostInvocation``/
    ``Stop``.
  * Antigravity **command** (shell) hooks run but cannot inject model context via stdout —
    injection (``HookInjectedStep``) is wired only for its SDK / declarative callers, not
    ``jsonhook`` command hooks (verified empirically).

Antigravity *does* auto-load ``AGENTS.md`` at session start and surfaces its content with no
tool call (verified: agy quoted this block, incl. the latest decision). A forwarder ("read
.ai/memory/X") is NOT reliable — agy would have to issue a tool call to read it, and that can
be blocked by Code Brain's own PreToolUse routing (e.g. a grep reroute). So the block must be
INLINE in the auto-loaded file. To avoid git churn from rewriting a tracked file every turn,
``AGENTS.md`` is git-IGNORED (install seeds it + adds it to the target .gitignore); durable,
user-authored instructions live in the tracked ``.ai/AGENTS.md`` instead. The block content is
produced by the same ``build_context("SessionStart", ...)`` Claude/Codex get.

Safety: never raise into the hook hot path (callers wrap in try/except), write only when the
rendered block changed, opt-out via ``AI_AGENTS_MD_MEMORY=0``.
"""
from __future__ import annotations

import os
from pathlib import Path

START = "<!-- CODE-BRAIN:MEMORY:START (auto-generated by Code Brain; do not edit by hand) -->"
END = "<!-- CODE-BRAIN:MEMORY:END -->"
_HEADING = "## Code Brain — cross-agent 메모리 스냅샷 (세션 시작 시 자동 로드)"
_SUPPRESS_ENV = (
    "AI_SKILL_RECOMMENDATIONS",
    "AI_AGENT_RECOMMENDATIONS",
    "AI_PRECALL_RECOMMENDATIONS",
)


def enabled() -> bool:
    return os.environ.get("AI_AGENTS_MD_MEMORY", "1").lower() not in {"0", "false", "no", "off"}


def render_block(root: Path) -> str:
    """Build the memory body — the same content Claude/Codex get at SessionStart.

    Recommendation sections are suppressed (as for Claude/Codex's SessionStart command).
    The transient ``Code Brain fast_path:`` header line is dropped.
    """
    saved = {k: os.environ.get(k) for k in _SUPPRESS_ENV}
    for k in _SUPPRESS_ENV:
        os.environ[k] = "0"
    try:
        from .hooks import build_context

        body = build_context("SessionStart", {"agent": "antigravity", "dry": True}, root=root)
    finally:
        for k, v in saved.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v
    if not body:
        return ""
    lines = body.split("\n")
    if lines and lines[0].startswith("Code Brain fast_path:"):
        lines = lines[1:]
        while lines and not lines[0].strip():
            lines = lines[1:]
    return "\n".join(lines).strip()


def compose(existing: str, block: str) -> str:
    """Return ``existing`` with the managed section set to ``block`` (idempotent)."""
    section = f"{START}\n{_HEADING}\n\n{block}\n{END}"
    if START in existing and END in existing:
        pre = existing.split(START, 1)[0]
        post = existing.split(END, 1)[1]
        return f"{pre.rstrip()}\n\n{section}\n{post.lstrip()}".rstrip() + "\n"
    return f"{existing.rstrip()}\n\n{section}\n"


def refresh(root: Path, *, path: str = "AGENTS.md") -> bool:
    """Refresh the managed block in ``<root>/AGENTS.md`` (git-ignored). Returns True if
    written. No-op (False) when disabled, when there is no memory, or when unchanged."""
    if not enabled():
        return False
    block = render_block(root)
    if not block:
        return False
    target = root / path
    existing = target.read_text(encoding="utf-8") if target.exists() else "# AGENTS.md\n"
    new_text = compose(existing, block)
    if target.exists() and existing == new_text:
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(new_text, encoding="utf-8")
    return True
